# -*- coding: utf-8 -*-
"""데이터 전처리.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iKDtIs-iJk7QxjI1pjbH2-1YgXKDwn2i
"""

import pandas as pd

# CSV 파일 경로 설정 (한글 파일명도 문제없이 읽힙니다)
file_path = "/content/수정구_건물데이터.csv"

# CSV 파일을 읽어옵니다 (인코딩을 CP949로 지정)
df = pd.read_csv(file_path, encoding='CP949')

# 데이터프레임 출력
print(df.head())

unique_values = df["주요용도명"].unique()
print(unique_values)

# "주요용도명" 열이 "단독주택" 또는 "공동주택"인 행만 필터링
filtered_df = df[df["주요용도명"].isin(["단독주택", "공동주택"])]

# 필터링된 데이터프레임 출력
print(filtered_df)

